### ISSUE TITLE
Suggestion - enable discussions in the repo

### ISSUE THREAD

**Issue by vladiliushin** [danyi1212/celery-insights#44]
Hi,

great project! 

README reffers to "Discussions" for the question and/or discussions, but the repo does not have discussions enabled. 

Would be helpful for generic questions like "If flower is able to parse the arguments for tasks and celery-insights have arguments always as `{args:[]kwargs:{}}`, what can be the cause?".

**Comment by danyi1212** [comment]
Great suggestion! I've added Github Discussions to the repo, see you there? 🙂🚀

**Comment by danyi1212** [comment]
Great suggestion! I've added Github Discussions to the repo, see you there? 🙂🚀
