### ISSUE TITLE
[BUG] MAX_TASKS & MAX_WORKERS env vars don't seem to work

### ISSUE THREAD

**Issue by angelmadames** [danyi1212/celery-insights#49]
First of all, thank you for your hard work creating Celery Insights. I see myself using it in favor Flower in the future!

## Bug summary
I'm currently deploying to an Azure Container App and setting the MAX_TASKS and MAX_WORKERS environment variables, but they don't seem to have an effect on the app.

In the settings page, the numbers don't represent either the default values mentioned in the doc, nor the values I put in the env vars.

## Settings page screenshot

![image](https://github.com/user-attachments/assets/ed6437c4-85e2-4852-b201-cf7b387177bf)

## Env Vars screenshot

![image](https://github.com/user-attachments/assets/1327653d-127f-4be2-b05d-90dfa7455978)

## Default values according to code screenshot

![image](https://github.com/user-attachments/assets/0f6785b1-d575-4b04-901b-fa79b21b8596)

I'm happy to contribute with a fix, but I am not sure where the root cause of the problem is. If you can provide directions, I'd be more than willing to help fix this as it is hugely beneficial for a project I'm working on.

Thanks!

**Comment by danyi1212** [comment]
The configurations you've mentioned configure the Tasks and Workers Memory in the server, while the screenshot included is for the memory in the browser (client).

The server can be dynamically configured to remember more / less tasks and workers (with increased memory costs), while the browser cache only the latest tasks and workers and reloads older tasks from the server only when used. This is to preserve the valuable browser memory.

Note that this is explained while hovering the setting, while the server's state memory is shown on the right. 
![image](https://github.com/user-attachments/assets/ee07e70b-ebaa-4010-ae2f-d07edbb05905)
